/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PackageType = IDL.Variant({
  'premium' : IDL.Null,
  'custom' : IDL.Null,
  'standard' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'packageType' : PackageType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'priceInCents' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const FormLead = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'packagePaid' : IDL.Bool,
  'packageType' : PackageType,
  'productPaid' : IDL.Bool,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'caller' : IDL.Principal,
});
export const Lead = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ChatbotLead = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'chatHistory' : IDL.Opt(IDL.Vec(IDL.Text)),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFreeTrial' : IDL.Func([], [IDL.Bool], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'forms' : IDL.Vec(FormLead),
          'freeTrialClaimed' : IDL.Bool,
          'orders' : IDL.Vec(Order),
          'leads' : IDL.Vec(Lead),
          'chatbotLeads' : IDL.Vec(ChatbotLead),
        }),
      ],
      [],
    ),
  'getFileReference' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFileReference' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitChatbotLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Text))],
      [ChatbotLead],
      [],
    ),
  'submitFormLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [FormLead], []),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Lead], []),
  'submitOrder' : IDL.Func(
      [PackageType, IDL.Text, IDL.Bool, IDL.Bool],
      [Order],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PackageType = IDL.Variant({
    'premium' : IDL.Null,
    'custom' : IDL.Null,
    'standard' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'packageType' : PackageType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'priceInCents' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const FormLead = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'packagePaid' : IDL.Bool,
    'packageType' : PackageType,
    'productPaid' : IDL.Bool,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'caller' : IDL.Principal,
  });
  const Lead = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ChatbotLead = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'chatHistory' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFreeTrial' : IDL.Func([], [IDL.Bool], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'forms' : IDL.Vec(FormLead),
            'freeTrialClaimed' : IDL.Bool,
            'orders' : IDL.Vec(Order),
            'leads' : IDL.Vec(Lead),
            'chatbotLeads' : IDL.Vec(ChatbotLead),
          }),
        ],
        [],
      ),
    'getFileReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFileReference' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitChatbotLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Text))],
        [ChatbotLead],
        [],
      ),
    'submitFormLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [FormLead], []),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Lead],
        [],
      ),
    'submitOrder' : IDL.Func(
        [PackageType, IDL.Text, IDL.Bool, IDL.Bool],
        [Order],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };